### PR TITLE
Reorganize snakebids directory

### PR DESCRIPTION
**Pull request by pvandyken**
As discussed in #62, the `__init__.py` file should not be used to store code, but rather just for managing imports. This PR moves the code within the file to `bids.py`.

I added a new tool I like to use to manage `__init__.py` files: [`mkinit`](https://pypi.org/project/mkinit/). It allows you easily specify which modules should be imported into the `__init__.py` file using `__submodules__=[...]`. It takes care of all the code to accomplish that, putting it within the `<AUTOGEN_INIT>` tags. The tool can be called using the `poe mkinit` command, which I programmed into the `pyproject.toml` file. 

I also reorganized the main directory a bit, moving `outputs.py` and `snakemake_io.py` into a new `utils/` directory.

Finally, I ran `poetry update`, so anything that could be updated within our constraints was.

Note that I had to manually change the issue specified in `pyproject.toml` to prevent an error, as per #86. 

Address issue #62

### CODE REVIEW

**Review by akhanf — APPROVED** [review]
Looks good to me

**Review by kaitj — COMMENTED** [review]
Overall looks good to me - just one question.

Is `pybids` still being imported anywhere other than in `snakebids/bids.py`? I only saw it imported in the testcases, which isn't a big deal. Just wouldn't want any confusion between `snakebids/bids.py` (relative import) and `pybids`.

There will be a merge conflict due to the version in `pyproject.toml`. I believe #88 bumped it to `0.4.0-pre.2` after the merge.

**Comment by kaitj** [comment]
> @kaitj I'm open to changing the name of the file, although we already have a function within the now `bids.py` file called `bids()`. All of the functions in `bids.py` are imported into `__init__.py`, so they can still be directly imported into projects. Let me know if you have any suggestions

Don't know if we necessarily need to change it if `pybids` isn't being called elsewhere. Will think about this some more.

**Review by kaitj — APPROVED** [review]

**Comment by pvandyken** [comment]
> Looks good to me. One question: Why aren't we including `app.py` in the init file?

@tkkuehn Simply because it wasn't included before. Happy to do so now (with the realization that it will make everything in app available under `snakebids.x`

**Comment by tkkuehn** [comment]
> > Looks good to me. One question: Why aren't we including `app.py` in the init file?
> 
> @tkkuehn Simply because it wasn't included before. Happy to do so now (with the realization that it will make everything in app available under `snakebids.x`

Makes sense! I wasn't thinking about it that way but that seems totally reasonable. Feel free to merge from my end!

**Pull request merged**
