### PR TITLE
Manual Release by Committish

### PR DESCRIPTION
**Pull request by kaitj**
## Proposed changes

- Adds a separate config for release-drafter
- Updates workflow to require a commitish value that is passed along for
release-drafter
- Sets manual release-drafter to use 'release-drafter-manual.yml'
configuration, which includes the `filter-by-commitish`

## Checklist

Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you are unsure about any of the choices, don't hesitate to ask!

- [ ] Changes have been tested to ensure that fix is effective or that a feature works.
- [ ] Changes pass the unit tests
- [ ] I have included necessary documentation or comments (as necessary)
- [ ] Any dependent changes have been merged and published

## Notes
All PRs will undergo the unit testing before being reviewed. You may be requested to explain or make additional changes before the PR is accepted.

### CODE REVIEW

**Comment by pvandyken** [comment]
Okay, I did a bunch of playing around and testing, and found that I could make a single generic bump-version, release-drafter, and deployment workflow. The bump-version just takes whatever branch is being PRed "into" and uses that as the commitish and basis for version bumping. For deploy, you get the ability to specify what branch you'd like to deploy. The relevant commit can be found [here](https://github.com/pvandyken/snakebids/commit/8f49c7ba821904434b68e3659da909ae966df973). For the keep the changes here, but there's no need for the separate `release-drafter.yml`. Just make sure that the original `release-drafter.yml` gets the `filter-by-commitish: True` line.

**Comment by pvandyken** [comment]
The only caveat is that, lets stay you start a new branch (like `v0.4.x`), and then you want to PR something into that new branch. You need to go back to the releases and manually change the target commitish of a relevant release to point to that new branch. Otherwise there will be nothing pointing at the branch, and your new PR will get a draft release version of `v0.1.0`.

**Comment by kaitj** [comment]
> The bump-version just takes whatever branch is being PRed "into" and uses that as the commitish and basis for version bumping. 

Just wrapping my head around this - so it would still bump the version in `main` if a PR is made to merge some branch into `main`? 

> For deploy, you get the ability to specify what branch you'd like to deploy. 

This sounds good. I took a quick look at the code too - you only need to specify `required: true` as `false` is default behaviour.

> The only caveat is that, lets stay you start a new branch (like v0.4.x), and then you want to PR something into that new branch. You need to go back to the releases and manually change the target commitish of a relevant release to point to that new branch. Otherwise there will be nothing pointing at the branch, and your new PR will get a draft release version of v0.1.0.

I don't think this is too much of an issue for this development (at least at the moment). 

Code wise this looks good to me, and other than my confusion with the version bumping, seems like a good resolution. If this looks good to everyone else, I would say feel free to push your changes into this branch @pvandyken and we can switch the assignee / reviewers around to get this merged in (or we can close this and open a new PR, whichever is easier).

**Comment by pvandyken** [comment]
> This sounds good. I took a quick look at the code too - you only need to specify `required: true` as `false` is default behaviour.

My IDE was getting mad at the missing required tag, so I added it. Obviously not actually necessary though.

> Just wrapping my head around this - so it would still bump the version in main if a PR is made to merge some branch into main?

Yes, so all PRs have a "base" branch: the branch you merge into. That "base" will be the one used in the workflow: so it will clone the "base" reference, use "base" for commitish in release-drafter, update the version based on whatever it finds in "base", and push back into "base". So long as you merge into `main`, everything will be the same.

**Comment by kaitj** [comment]
Closing this in favour of #165.

**Pull request closed without merging**
