### PR TITLE
Update cookiecutter for injection vulnerability

### PR DESCRIPTION
**Pull request by pvandyken**
See https://security.snyk.io/vuln/SNYK-PYTHON-COOKIECUTTER-2414281

Addresses #173

### CODE REVIEW

**Comment by tkkuehn** [comment]
Build is failing because of this: https://status.python.org/incidents/lgpr13fy71bk

The code looks good but I will reserve approval until the test workflow runs through.

**Comment by pvandyken** [comment]
Ah, I was wondering why nothing `pip` related was working

**Review by kaitj — APPROVED** [review]
Looks good to me - don't think it would break anything. We can consider making this a release on its own so alerts for repos making use of snakebids can also be resolved (e.g. #173).

**Comment by pvandyken** [comment]
Good call, I'll go ahead and make the release

**Pull request merged**
