### PR TITLE
Restrict pybids bug check to python 3.7

### PR DESCRIPTION
**Pull request by pvandyken**
Now merging through the proper channels!

The underlying [issue](https://github.com/bids-standard/pybids/issues/788) does appear to be resolved, so I restricted the failing test to py37, where it's still relevant (because we can't install the latest version of pybids on py37)

### CODE REVIEW

**Review by tkkuehn — APPROVED** [review]

**Comment by pvandyken** [comment]
Just a flaky hypothesis test (due to test timings). A re-run usually solves it. Not ideal, but seems to be the nature of the beast

**Comment by kaitj** [comment]
Lgtm, though now the docs are failing to build (dependency conflicts?)

On the failure, is there a way to set the maximum runtime for the tests? Highly doubt it would happen (knock on wood), but could it ever happen where re-runs will fail for at least 1 python version causing it the checks to repeatedly fail. Not a big deal in any case if the re-run will solve the issue and don't want to limit the testing either.

**Review by kaitj — APPROVED** [review]

**Comment by pvandyken** [comment]
> Highly doubt it would happen (knock on wood)

Too late, you've jinxed it! I've increased the deadline for the two flaky tests.

**Comment by pvandyken** [comment]
On the strictly maintenance front, I added a `poe fix` command that applies `ruff` autofixes

**Comment by pvandyken** [comment]
Okay, this turned into sort of an omnibus issue, but I think everything is sorted. I don't know why the tests were flaking so much... maybe the git actions runner was hanging?

The only other thing I did was fix some of my tests which were calling `strategy.example` directly. Turns out you can just set the `max_example` parameter in `setting` to 1, so that's what I did

**Pull request merged**
