### PR TITLE
Remove dependency upper-caps and update

### PR DESCRIPTION
**Pull request by pvandyken**
Remove cached-property dep since functionality is provided by functools in py38

Remove all upper version limits in main dependency block. Where kept, justification comment is added

Upgraded pvandyken-deprecated dependency, which packages proper typing support (thus, remove our own typings file)

### CODE REVIEW

**Review by kaitj — APPROVED** [review]
Largely lgtm code-wise (just realized the one test is failing for py3.11), with a very minor comment (that upon second thought doesn't really require any action given these are more dev dependencies than for distribution).

Aside from `cookiecutter` (which will get replaced in #336 anyway), is there opposition to changing the `^` to a `>=`?. The caret requirements would be placing an upper-cap on the dependencies if I am interpreting the poetry docs correctly. Making the change would also bring us closer to following [PEP440](https://peps.python.org/pep-0440/).

**Comment by pvandyken** [comment]
> Aside from cookiecutter (which will get replaced in https://github.com/akhanf/snakebids/pull/336 anyway), is there opposition to changing the ^ to a >=?. The caret requirements would be placing an upper-cap on the dependencies if I am interpreting the poetry docs correctly. Making the change would also bring us closer to following [PEP440](https://peps.python.org/pep-0440/).

For a specific dependency, or for everything? And are you asking about removing the `^` from a syntax perspective (and replacing with `>=x,<y`), or just on removing upper limits?

**Comment by pvandyken** [comment]
The test failure should be fixed by a commit I made in #336, so I'll wait for that one to merge, then deal with the failure here

**Comment by kaitj** [comment]
> > Aside from cookiecutter (which will get replaced in #336 anyway), is there opposition to changing the ^ to a >=?. The caret requirements would be placing an upper-cap on the dependencies if I am interpreting the poetry docs correctly. Making the change would also bring us closer to following [PEP440](https://peps.python.org/pep-0440/).
> 
> For a specific dependency, or for everything? And are you asking about removing the `^` from a syntax perspective (and replacing with `>=x,<y`), or just on removing upper limits?

More a general thing and yeah, replacing `^` with `>=x` (and `<y` where it is needed)

**Review by tkkuehn — APPROVED** [review]
Pending tests passing this looks good

**Comment by pvandyken** [comment]
I'm going to keep the `^` syntax for the dev dependencies, just because it's more concise and imo upper limits are at least not harmful for dev dependencies. Pending the test passing I'm going to merge

**Pull request merged**
